# STAGE 1
FROM node:lts
WORKDIR /usr/src/app
COPY package*.json ./ 

# Install
RUN npm install 

# Install typescript 
RUN npm install -g typescript 

COPY . . 

# STAGE 2 : WAIT POSTGRESS
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

# Expose the port
EXPOSE 3030

# Run tests in order to fill the database
CMD ["npm", "test"]

# STAGE 3 : RUN 
CMD ["npm", "start"]