version: '3'

services:
  api:
    build:
      context: .
    environment:
      WAIT_HOSTS: postgres:5432
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: vTpbcHcb
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "3030:3030"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: vTpbcHcb
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
    - db-volume:/var/lib/postgresql/data
    ports:
    - 5432:5432

volumes:
  db-volume: